### ISSUE TITLE
Publish this plugin in npm

### ISSUE THREAD

**Issue by davidyuk** [airgap-it/cordova-plugin-airgap-secure-storage#1]
Or it is already published there? I have checked `cordova-plugin-airgap-secure-storage` as in package.json, npm can't find it.

**Comment by lukeisontheroad** [comment]
We published the plugin on npmjs yesterday: https://www.npmjs.com/package/cordova-plugin-airgap-secure-storage

You can install it with a simple 

`npm i cordova-plugin-airgap-secure-storage`
