### ISSUE TITLE
Is this plugin better than `cordova-plugin-secure-storage`?

### ISSUE THREAD

**Issue by davidyuk** [airgap-it/cordova-plugin-airgap-secure-storage#2]
What are the benefits of the usage of this plugin instead of [`cordova-plugin-secure-storage`](https://www.npmjs.com/package/cordova-plugin-secure-storage)?

API and purpose of this plugins look similar. `cordova-plugin-secure-storage` started developed earlier than this one, and it is still maintaining (latest version released five days ago). It is also [supported by Ionic](https://ionicframework.com/docs/native/secure-storage/). For me is unclear why you decided to implement own secure storage plugin.

**Comment by dcale** [comment]
cordova-plugin-secure-storage does not use biometrics to authenticate the lock/unlock of entries. On Android it uses the old RSA Keystore implementation. We did not "just" want to store stuff in the device's secure storage but also require an authentication via biometrics when accessing the stuff.

Is it better? I don't know how to answer that, it's different. One plugin unlocks the secure storage "just like that" (cordova-plugin-secure-storage) the other requires the User's Authentication to unlock the storage (cordova-plugin-airgap-secure-storage).
